### ISSUE TITLE
glPortal will not build against bullet 2.86

### ISSUE THREAD

**Issue by willysr** [GlPortal/glPortal#53]
Hi

i tested glPortal against bullet 2.86 and it will not build with this error message:

```
[ 87%] Building CXX object source/CMakeFiles/glportal.dir/engine/physics/PhysicsHelper.cpp.o
[ 87%] Building CXX object source/CMakeFiles/glportal.dir/engine/physics/Uncollider.cpp.o
/tmp/SBo/glPortal-c3d5e47c5151360c09d0d84f66d9c0e3c2051251/source/engine/physics/Uncollider.cpp: In static member function ‘static void glPortal::Uncollider::nearCallback(btBroadphasePair&, btCollisionDispatcher&, const btDispatcherInfo&)’:
/tmp/SBo/glPortal-c3d5e47c5151360c09d0d84f66d9c0e3c2051251/source/engine/physics/Uncollider.cpp:53:80: error: no matching function for call to ‘btCollisionDispatcher::findAlgorithm(btCollisionObjectWrapper*, btCollisionObjectWrapper*)’
       collisionPair.m_algorithm = dispatcher.findAlgorithm(&obj0Wrap, &obj1Wrap);
                                                                                ^
In file included from /usr/include/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.h:83:0,
                 from /usr/include/bullet/btBulletCollisionCommon.h:22,
                 from /usr/include/bullet/btBulletDynamicsCommon.h:20,
                 from /tmp/SBo/glPortal-c3d5e47c5151360c09d0d84f66d9c0e3c2051251/source/assets/scene/Scene.hpp:7,
                 from /tmp/SBo/glPortal-c3d5e47c5151360c09d0d84f66d9c0e3c2051251/source/engine/physics/Uncollider.hpp:5,
                 from /tmp/SBo/glPortal-c3d5e47c5151360c09d0d84f66d9c0e3c2051251/source/engine/physics/Uncollider.cpp:1:
```

**Comment by hhirsch** [comment]
Thank you for reporting. @SGOrava Same message that our Mac build fails with.

**Comment by hhirsch** [comment]
@willysr The Version we are using is 2.85. cmake did not complain?

**Comment by SGOrava** [comment]
@hhirsch We are checking if the version is 2.85 or higher.

**Comment by willysr** [comment]
@hhirsch : i was the maintainer of bullet in SlackBuilds project and i bumped to 2.86 before i realize that glPortal does not work with 2.86, thus i reported this upstream.

I can postpone the update for bullet though if glPortal needs time to test for 2.86 compatibility.

**Comment by hhirsch** [comment]
@willysr You'll find a playable version of GlPortal on the stable branch. It does require bullet < 2.85 iirc.
Current master is not playable. 

As we like to keep GlPortal Libraries up to date we will switch to 2.86 asap.

**Comment by willysr** [comment]
I'm pending the bullet update for now.
Ping me when glPortal already support bullet 2.86.

Thanks

**Comment by hhirsch** [comment]
@willysr Thank you for your feedback. If there is something more we can do, please let us know.

**Comment by willysr** [comment]
Shouldn't this bug left open so that it can be a reminder for Developers?

**Comment by hhirsch** [comment]
@willysr We'll be reminded automatically when our distribution catches up with the newest bullet development so having this issue will not make a difference to when we are going to fix it. 

However I can clearly see that you are very interested in how we progress in our bullet integration so I will reopen it that you will stay up-to-date on the issue. Thank you again for engaging with us.

**Comment by willysr** [comment]
Thanks, i will try to find some time to test this tree

**Comment by willysr** [comment]
confirmed to be working
once those branch has been merged to master, you can close this issue.

Thanks

**Comment by Geertiebear** [comment]
Can we close this? It works properly now.

**Comment by willysr** [comment]
if the patch has been merged in master, this issue can be closed

**Comment by hhirsch** [comment]
Yes. Current master will work with 2.86 and most older Bullet Versions
